# Generated by Django 4.2.2 on 2023-06-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='titile',
        ),
        migrations.AddField(
            model_name='notes',
            name='title',
            field=models.CharField(blank=True, max_length=2001),
        ),
        migrations.AlterField(
            model_name='notes',
            name='description',
            field=models.TextField(),
        ),
    ]
